### ISSUE TITLE
How to implement NotificationRequest using Filters ?

### ISSUE THREAD

**Issue by Gys** [tbalthazar/onesignal-go#3]
I am trying to create a notification using a filter for emails. The `interface{}` definition of the Filters field is puzzling me.

I tried the implementation below, but that results in `Couldn't decode response body JSON`. If I use the `IncludePlayersIDs` instead then the notification works well. So the problem is really in my Filters implementation.

Any suggestions ?

	notificationReq := &onesignal.NotificationRequest{
		AppID:    client.AppKey,
		Contents: map[string]string{"en": "English message"},
		IsIOS:    true,
		// IncludePlayerIDs: []string{playerID},
	}

	if err := json.Unmarshal([]byte(`[{"field":"email", "value":"test@domain.com"}]`), &notificationReq.Filters); err != nil {
	 	return err
	}

**Comment by Gys** [comment]
`Couldn't decode response body JSON` is an internal error - missed that one, sorry.

The actual message from OneSignal is `Please include a case-sensitive header of Authorization: Basic <YOUR-REST-API-KEY-HERE> with a valid REST API key.`

This package only has fields for the App ID and the User Auth Key. But OneSignal also provides a REST API key which is required in this request ?

**Comment by Fyb3roptik** [comment]
Did you submit a PR?

**Comment by CraigChilds94** [comment]
@Gys I'd like to think you've figured it out now, really it's a `[]map[string]string`, you can basically send it in the format which is specified in One Signals docs. Like so:

```
[]map[string]string{{"field": "field_name", "relation": "=", "value": "value_to_compare"}}
```

**Comment by Gys** [comment]
@CraigChilds94 Yes, I had figured it out, thank you for getting back to it.
